events {
    worker_connections 1024;
}

http {
    # 1. Definição das Zonas (Webhook e Admin separadas)
    limit_req_zone $binary_remote_addr zone=webhook_limit:10m rate=3r/s; # Aumentei um pouco para evitar perda de msg
    limit_req_zone $binary_remote_addr zone=admin_limit:10m rate=1r/s;   # Rígido para o Admin

    resolver 127.0.0.11 valid=5s; 

    # Upstream Django (Porta 8000)
    upstream django_app {
        server django-web:8000; # Use o nome exato do serviço no compose
    }

    # Upstream Go Gateway (Porta 8080)
    upstream go_gateway_app {
        zone go_app_state 64k; 
        server go-gateway:8080 resolve; 
    }

    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    server {
        listen 80;
        server_name seu_dominio.com www.seu_dominio.com;

        # Headers de Segurança Globais
        add_header X-Frame-Options "SAMEORIGIN";
        add_header X-Content-Type-Options "nosniff";
        add_header X-XSS-Protection "1; mode=block";

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        location /static/ {
            alias /app/staticfiles_dist/;
            expires 30d;
            add_header Cache-Control "public, no-transform";
        }
        
        location /webhook {
            proxy_set_header X-Webhook-Hmac $http_x_webhook_hmac;
            client_max_body_size 1m; 
            limit_req zone=webhook_limit burst=10 nodelay;
            proxy_pass http://go_gateway_app; 
        }

        location /portal-secreto-dev-m/ {
            limit_req zone=admin_limit burst=3 nodelay;
            proxy_pass http://django_app; 
        }

        location /control-quiro/ {
            limit_req zone=admin_limit burst=5 nodelay;
            proxy_pass http://django_app;
        }
        
        location / {
            proxy_pass http://django_app;
        }
    }
}