# Generated by Django 5.2.7 on 2025-12-17 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_api', '0002_logmetrica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logmetrica',
            name='status',
            field=models.CharField(choices=[('success', 'Sucesso'), ('failed', 'Falha'), ('pending', 'Pendente')], default='success', max_length=20),
        ),
        migrations.AlterField(
            model_name='logmetrica',
            name='tipo_metrica',
            field=models.CharField(choices=[('agendamento', 'Agendamento'), ('cancelamento', 'Cancelamento'), ('lembrete', 'Lembrete Enviado')], db_index=True, max_length=30),
        ),
    ]
