# Generated by Django 5.2.7 on 2025-12-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_api', '0003_alter_logmetrica_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleAuthConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_conta', models.EmailField(max_length=254, unique=True, verbose_name='E-mail Autorizador')),
                ('token_data', models.JSONField(blank=True, null=True, verbose_name='Dados do Token OAuth')),
                ('is_active', models.BooleanField(default=True, verbose_name='Integração Ativa')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração Google',
                'verbose_name_plural': 'Configurações Google',
                'db_table': 'google_auth_config',
            },
        ),
    ]
