# Generated by Django 5.2.7 on 2025-12-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_api', '0004_googleauthconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googleauthconfig',
            name='email_conta',
        ),
        migrations.AddField(
            model_name='googleauthconfig',
            name='email_admin',
            field=models.EmailField(default='maiconwantuil@gmail.com', max_length=254, unique=True, verbose_name='E-mail do Administrador'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='googleauthconfig',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='googleauthconfig',
            name='token_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Dados do Token'),
        ),
    ]
