# Generated by Django 5.2.7 on 2025-12-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_api', '0005_remove_googleauthconfig_email_conta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(default='waha_pode_iniciar', max_length=50, unique=True)),
                ('liberado', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='GoogleAuthConfig',
        ),
    ]
