# Generated by Django 5.2.7 on 2026-01-03 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_api', '0006_systemcontrol_delete_googleauthconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='appointment3_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora 3ª Consulta'),
        ),
        migrations.AddField(
            model_name='userregister',
            name='appointment3_gcal_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ID Google Calendar 3'),
        ),
        migrations.AddField(
            model_name='userregister',
            name='appointment4_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora 4ª Consulta'),
        ),
        migrations.AddField(
            model_name='userregister',
            name='appointment4_gcal_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ID Google Calendar 4'),
        ),
    ]
